apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-api-management/wasm-shim-product-build?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "rhcl-1.4"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rhcl-1-4-rhcl-operator
    appstudio.openshift.io/component: rhcl-1-4-wasm-shim
    pipelines.appstudio.openshift.io/type: build
  name: rhcl-1-4-wasm-shim-on-push
  namespace: api-management-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-4-wasm-shim:{{revision}}
  - name: dockerfile
    value: Containerfile.wasm-shim
  - name: prefetch-input
    value: '[{"type": "cargo", "path": "./wasm-shim"}, {"type": "rpm", "path": "."}]'
  pipelineRef:
    name: multi-arch-build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-rhcl-1-4-wasm-shim
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
